# yaml-language-server: $schema=https://raw.githubusercontent.com/Microsoft/vscode-python/master/schemas/conda-environment.json
name: resume
channels:
  - conda-forge
dependencies:
  - go-task
  - pre-commit
  - nodejs
  - elm
  # INFO: nodejs package build
  - python
  - make
  - setuptools
  - cxx-compiler
