version: "3"
vars:
  GIT_ROOT_PATH:
    sh: git rev-parse --show-toplevel
tasks:
  pwd: pwd
  install:
    cmds:
      - npm install
  render-pdf:
    # TODO: improve this task
    dir: "{{.GIT_ROOT_PATH}}/dist/"
    # env:
    #   DISPLAY: :9.0
    deps:
      - build
    sources:
      - ./**
      - exclude: "*.pdf"
    generates:
      - ./resume.pdf
    vars:
      RENDER_PDF_CMD_PREFIX:
        sh: |
          if command -v nix >/dev/null 2>&1; then
            echo 'nix develop --command -- steam-run env TMPDIR=/tmp xvfb-run -a'
          elif command -v xvfb-run >/dev/null 2>&1; then
            echo 'xvfb-run -a'
          else
            echo ''
          fi
    cmds:
      - pwd
      - ls -la
      - >-
        {{.RENDER_PDF_CMD_PREFIX}} npx electron-pdf "$(pwd)/index.html" "$(pwd)/resume.pdf"
      - ls -la resume.pdf
  build:
    sources:
      - ./src/**
    generates:
      - ./dist/**
      - exclude: "*.pdf"
    cmds:
      - npx parcel build --public-url "./" --no-scope-hoist src/index.html
  dev:
    cmds:
      - npx parcel serve src/index.html
  upgrade:
    cmds:
      - npm update
  clean:
    cmds:
      - rm -rf dist
  clean-all:
    deps:
      - clean
    cmds:
      - rm -rf node_modules .cache .parcel-cache elm-stuff
  reinstall:
    cmds:
      - rm -rf node_modules
      - rm -rf elm-stuff
      - task: install
  lint:
    cmds:
      - npx elm-analyse
      - npx elm-format --validate src/
      - npx stylelint src/**.scss
