version: "3"
tasks:
  install:
    cmds:
      - npm install
  build:
    cmds:
      - npx parcel build --public-url "./" --no-scope-hoist src/index.html
  dev:
    cmds:
      - npx parcel serve src/index.html
  upgrade:
    cmds:
      - npm update
  clean:
    cmds:
      - rm -rf dist
  clean-all:
    deps:
      - clean
    cmds:
      - rm -rf node_modules .cache .parcel-cache
  reinstall:
    cmds:
      - rm -rf node_modules
      - rm -rf elm-stuff
      - task: install
  lint:
    cmds:
      - npx elm-analyse
      - npx elm-format --validate src/
      - npx stylelint src/**.scss
